### ISSUE TITLE
[1.12.2] Varies issues when used with certain mods.

### ISSUE THREAD

**Issue by SonicX8000** [CaliforniaDemise/Bubbles#1]
I tried giving this fork a go and I ran into a number of issues. Here's a rundown.

Mods:
Baubles-1.12-pre2.0-bubbles
HadEnoughItems_1.12.2-4.25.2

---

1. RLArtifacts-1.1.2
https://legacy.curseforge.com/minecraft/mc-mods/rl-artifacts

Causes the inventory to not render correctly and also the log gets endlessly spammed.

Log File:
[latest.log](https://github.com/CaliforniaDemise/Bubbles/files/14817913/latest.log)

Debug File:
[debug.log](https://github.com/CaliforniaDemise/Bubbles/files/14817915/debug.log)

---

2. WearableBackpacks-RLCraft-1.12.2-3.2.6
https://legacy.curseforge.com/minecraft/mc-mods/wearable-backpacks-rlcraft-edition

Crashes upon load, prob due to the baubles support. (This happens even if baubles support is disabled in the config)

Crash:
[crash-2024-03-31_18.34.55-server.txt](https://github.com/CaliforniaDemise/Bubbles/files/14817925/crash-2024-03-31_18.34.55-server.txt)

Log:
[latest.log](https://github.com/CaliforniaDemise/Bubbles/files/14817927/latest.log)

Debug:
[debug.log](https://github.com/CaliforniaDemise/Bubbles/files/14817928/debug.log)

---

3. Botania+r1.10-362
https://legacy.curseforge.com/minecraft/mc-mods/botania

Many of the Baubles from this mod don't work prob due to them being hardcoded to one slot. For example... Cloak of Virtue which nulls almost any damage taken when you get hit will not block the damage when worn. The Tainted Blood Pendents do seem to work as they apply potion effects when wearing two of them. Rings seem to work too prob due to there being two ring slots and not a single slot.

---

Will add more to this issue as I go through the mods that add in baubles.

**Comment by CaliforniaDemise** [comment]
RLArtifacts is fixed, For Wearable Backpacks I requested a pr to it, so please ask fonnymonkey to push it. And about Botania, I guess I will fork Botania because it doesn't worth hussle and workarounds to fix it, if you want to use it for now don't remove or replace slots with different bauble types.

Waiting for more issues. Thanks for finding them!

**Comment by SonicX8000** [comment]
With a private modpack that I have... there's many mods that add in Baubles and currently after removing the above mods to get around crashes & such. One issue that I'm running into is my character hanging in the air, softlocking the world. I'ma name the mods that add in baubles.

```
AE2 Unoffical Extended Life (Prob also applies for the non-fork of Applied Enegertics 2?)
---
Astral Sorcery
---
Blood Arsenal
---
Natural Pledge (Botania Addon)
---
ExtraBotany (Botania Addon)
---
Cyclic
---
Dark Utilities
---
Draconic Evolution
---
Draconic Additions (Draconic Evolution Addon)
---
Electroblob's Wizardry
---
Elrctroblob's WIzardry: Twilight Forest Spell Pack
---
AncientSpellcraft
---
Embers Unoffical Extended Life
---
Aetherworks (Embers Addon)
---
EnderIO
---
Extra Utilities 2
---
Immersive Engineering
---
Industrial Foregoing
---
ProjectE
---
Quark: RotN Edition
---
Random Things
---
Redstone Repository
---
Refined Storage
---
Roots
---
Simply Backpacks
---
Tetra
---
Thaumcraft
---
Thaumic Periphery (Thaumcraft Addon)
---
The One Probe
---
Thermal Expansion
---
Thermal Innovation
---
Twilight Forest (I might have a mod that makes the Charm of Keeping a bauble? Unsure)
```

These are what I have installed currently. I would have to go through them one by one to see what issues arise. Here's one of them at least for now.

---Natural Pledge (Botania Addon)---
Landing causes a softlock for the world. If mobs try to melee you... they disappear while projectiles will pass right through you.

Latest:
[latest.log](https://github.com/CaliforniaDemise/Bubbles/files/14849690/latest.log)

Debug:
[debug.log](https://github.com/CaliforniaDemise/Bubbles/files/14849692/debug.log)

**Comment by CaliforniaDemise** [comment]
okay. Try the newest version

**Comment by CaliforniaDemise** [comment]
Closing this as completed because you didn't post new issues that occur after the fix. Mods shouldn't crash if they don't do unnecessary casting like Wearable backpacks, but there might be mods that don't work well with changed slots (like botania) which I will either fork or PR the fixes to them. Don't hesitate to create an issue if you find a mod like that. Thank you!
