### ISSUE TITLE
2.1 version is considered 1.5 from other mods

### ISSUE THREAD

**Issue by Biviho** [CaliforniaDemise/Bubbles#10]
hi! it looks like version 2.1 is considered to be version 1.5 from other mods, stopping them from loading since is lower than the required version 1.5.2

it was also pointed out [here](https://github.com/CaliforniaDemise/Bubbles/issues/9) by looking at the image... i guess, that's not my language xD

![Nuova immagine bitmap](https://github.com/user-attachments/assets/6c2684de-d908-47c2-8d57-ecf64b27e4ea)

**Comment by touhouzun** [comment]
Well...sounds like a duplicated content, take a look at this dev:
[https://github.com/CaliforniaDemise/Bubbles/commit/b6dcacf3f2189f5ae99a935825d1e5f3211aba30](url)
Gradle: thinking of my story? xD

**Comment by Biviho** [comment]
Sorry, i missed that the issue was fixed in [this commit](https://github.com/CaliforniaDemise/Bubbles/commit/b6dcacf3f2189f5ae99a935825d1e5f3211aba30)

**Comment by erialsan** [comment]
Same issue. No improvement.
Please upload the latest commit as it seems to have solved the problem.
