### ISSUE TITLE
Crash with Wearable Backpacks: RLCraft Edition 

### ISSUE THREAD

**Issue by ShinyArmorYT** [CaliforniaDemise/Bubbles#17]
Can't equip backpack in body slot and causes a crash when attempting to do so in world:

https://github.com/user-attachments/assets/a54c2817-1cf7-4da1-bc22-b6a6aeae7065

Edit:

Oops, sorry, forgot the crash log:

https://mclo.gs/bUMHGwe

Also just found out about the unmerged pull request with the fix to the issue...

**Comment by CaliforniaDemise** [comment]
Fixed in [this commit](https://github.com/CaliforniaDemise/Bubbles/commit/fed8463a0f5d50524a42f13ae8b9adbc6fd2d4b2).
