### ISSUE TITLE
Config JSON loader calls the client-side Minecraft class on servers, causing crashes

### ISSUE THREAD

**Issue by bruberu** [CaliforniaDemise/Bubbles#2]
Currently, it appears that when the config is loaded, it attempts to get the game directory using the Minecraft class, which is only available on clients. This currently makes the mod unusable on servers. (As a side note, as you do more work on this mod, it can help to run a quick runServer before releasing versions, although it took a while for me to do this with my own mod.)

To fix this issue, I think you could do something like what GregTech CEu does at line 155 of this file: https://github.com/GregTechCEu/GregTech/blob/master/src/main/java/gregtech/api/worldgen/config/WorldGenRegistry.java

Here's the core error:
```net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Bubbles (baubles)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft
    at baubles.common.Config.initJsonConfig(Config.java:36)
    at baubles.common.Config.initialize(Config.java:32)
    at baubles.common.Baubles.preInit(Baubles.java:43)

**Comment by CaliforniaDemise** [comment]
Fixed in [this](https://github.com/CaliforniaDemise/Bubbles/commit/689ff53868186efb545a9f6003464712c1b8f42b)
