### ISSUE TITLE
Add Config to Remove Recipe Book

### ISSUE THREAD

**Issue by Redfire75369** [CaliforniaDemise/Bubbles#6]
Since the vanilla recipe book is not that important in modded with JEI/HEI, many modpacks remove the recipe book. However, it still shows up in the Baubles UI.
The below line of code would just need an if condition around it referring to the config to work.
https://github.com/CaliforniaDemise/Bubbles/blob/32c6874b8257cb42b36d297515a95424cfe7828b/src/main/java/baubles/client/gui/GuiPlayerExpanded.java#L88

**Comment by CaliforniaDemise** [comment]
In newer updates you will be able to disable the recipe book by installing No Recipe Book mod or activating Universal Tweaks' disable recipe book tweak.
