### ISSUE TITLE
suggestions with issues

### ISSUE THREAD

**Issue by touhouzun** [CaliforniaDemise/Bubbles#8]
（1）Pressing key_B（or others to make bauble gui open）doesn‘t work properly as expected，（there're simply no reacts，and nothing is opened at all，）which means keyboard reflect event is not imported ，written or ready yet.
（2）It would be more grateful to restore compatibility with mods like https://github.com/pau101/Wings and https://github.com/zlainsama/CosmeticArmorReworked which are still using original baubles as optional dependencies.

**Comment by CaliforniaDemise** [comment]
1. Fixed.
2. I don't know what kind of compatibility Cosmetic Armor has, I will add button support but it wasn't a thing in normal Baubles. On the other hand Wings... Let's just say I don't know why he did it like that. And also I hate how most mods want specific versions of mods that don't even update.

**Comment by touhouzun** [comment]
> 1. Fixed.
> 2. I don't know what kind of compatibility Cosmetic Armor has, I will add button support but it wasn't a thing in normal Baubles. On the other hand Wings... Let's just say I don't know why he did it like that. And also I hate how most mods want specific versions of mods that don't even update.

Well I feel a bit sorry for my little willfulness, when I tried to get a fork and learn how to type java... :(
and it's a pity that when one encounters “how most mods want specific versions of mods that don't even update”.
> “Add a way to make items bauble and modifying already existing baubles.”
Waiting for good news :)

**Comment by CaliforniaDemise** [comment]
> > 1. Fixed.
> > 2. I don't know what kind of compatibility Cosmetic Armor has, I will add button support but it wasn't a thing in normal Baubles. On the other hand Wings... Let's just say I don't know why he did it like that. And also I hate how most mods want specific versions of mods that don't even update.
> 
> Well I feel a bit sorry for my little willfulness, when I tried to get a fork and learn how to type java... :( and it's truly annoying when one encounters the situation about “how most mods want specific versions of mods that don't even update”.
> 
> > “Add a way to make items bauble and modifying already existing baubles.”
> 
> Waiting for good news :)

I don't know what you mean by willfulness but it's not a problem, no need to be sorry.
And specific version thing isn't a problem that's hard to fix, it's just mildly infuriating at best.
